### ISSUE TITLE
Error in is_scalar_character(hierachyVar1) :    argument "hierachyVar1" is missing, with no default

### ISSUE THREAD

**Issue by sdipti** [uRos2018/voronoiTreemap#7]
I am trying to use the voronoitreemap for my dataset but when I put in the following code:
`manu_data <- vt_export_json(vt_input_from_df(world_data))`

The following error shows up:
Error in is_scalar_character(hierachyVar1) : 
  argument "hierachyVar1" is missing, with no default

My dataset has 6 variables, as in the Example GDP file, the weights are numeric type and all others are character variables.

Kindly help. Thanks a lot!

**Comment by sdipti** [comment]
This error is showing up even when I try to run the codes with the 'Example GDP' dataset and 'canada' dataset. Can't understand the reason!

**Comment by sdipti** [comment]
I'm really sorry for bombarding with comments - I re-installed the package and this error doesn't show up now. It is now showing the following error:
Error in vt_create_node(inp[1, 1]) : 
  is_scalar_character(total_lab) is not TRUE

I'm sure, there's something missing from my codes or I might be doing something wrong. I'm new to R, would be very grateful if someone could help. Many thanks.

**Comment by alexkowa** [comment]
I am not sure what is happening since I don't know what is inside worldmap at this stage.
But does this work?
`vt_d3(vt_export_json(vt_testdata()))`

**Comment by sdipti** [comment]
This works for Example GDP dataset. But not with my dataset. 
My dataset has the h1 as Total, h2 has set1, set2, set 3. h3 has a list of industries which is same (repeating) in each set and the weights has corresponding values - the total adds up to 100. 

I tried the following code:
`vt_d3(vt_export_json(vt_input_from_df(dataset)))`

and the following error showed up:
Error in vt_create_node(inp[1, 1]) : 
  is_scalar_character(total_lab) is not TRUE

**Comment by pyarasid** [comment]
Getting the following error, with a different data, when i install the package from devtools:

Error in is_scalar_character(hierachyVar1) :
argument "hierachyVar1" is missing, with no default

And get the following error if i install package from cran:

Error in vt_create_node(inp[1, 1]) :
is_scalar_character(total_lab) is not TRUE

The package work fine on the same GDP and canada data. vt_d3(vt_export_json(vt_testdata()))  also works.

**Comment by bernhard-da** [comment]
@pyarasid  please provide a fully reproducible example so that we can look into the issue. thx.
