### ISSUE TITLE
Change text color in Legend

### ISSUE THREAD

**Issue by ghost** [uRos2018/voronoiTreemap#9]
How can I modify the color of the legend text?

**Comment by alexkowa** [comment]
this is not implemented in the R interface. It could be done by manipulating the resulting HTML object.

**Comment by fraupflaume** [comment]
This can be done by manipulating the HTML object while _in_ the R interface. [It was shown here](https://stackoverflow.com/questions/71748472/how-to-change-text-color-in-a-voronoitreemap-legend/71772462#71772462).
